local M = {}

M.register_digraphs = function()
  vim.cmd('execute "digraphs as " . 0x2090')
  vim.cmd('execute "digraphs es " . 0x2091')
  vim.cmd('execute "digraphs hs " . 0x2095')
  vim.cmd('execute "digraphs is " . 0x1D62')
  vim.cmd('execute "digraphs js " . 0x2C7C')
  vim.cmd('execute "digraphs ks " . 0x2096')
  vim.cmd('execute "digraphs ls " . 0x2097')
  vim.cmd('execute "digraphs ms " . 0x2098')
  vim.cmd('execute "digraphs ns " . 0x2099')
  vim.cmd('execute "digraphs os " . 0x2092')
  vim.cmd('execute "digraphs ps " . 0x209A')
  vim.cmd('execute "digraphs rs " . 0x1D63')
  vim.cmd('execute "digraphs ss " . 0x209B')
  vim.cmd('execute "digraphs ts " . 0x209C')
  vim.cmd('execute "digraphs us " . 0x1D64')
  vim.cmd('execute "digraphs vs " . 0x1D65')
  vim.cmd('execute "digraphs xs " . 0x2093')

  vim.cmd('execute "digraphs aS " . 0x1d43')
  vim.cmd('execute "digraphs bS " . 0x1d47')
  vim.cmd('execute "digraphs cS " . 0x1d9c')
  vim.cmd('execute "digraphs dS " . 0x1d48')
  vim.cmd('execute "digraphs eS " . 0x1d49')
  vim.cmd('execute "digraphs fS " . 0x1da0')
  vim.cmd('execute "digraphs gS " . 0x1d4d')
  vim.cmd('execute "digraphs hS " . 0x02b0')
  vim.cmd('execute "digraphs iS " . 0x2071')
  vim.cmd('execute "digraphs jS " . 0x02b2')
  vim.cmd('execute "digraphs kS " . 0x1d4f')
  vim.cmd('execute "digraphs lS " . 0x02e1')
  vim.cmd('execute "digraphs mS " . 0x1d50')
  vim.cmd('execute "digraphs nS " . 0x207f')
  vim.cmd('execute "digraphs oS " . 0x1d52')
  vim.cmd('execute "digraphs pS " . 0x1d56')
  vim.cmd('execute "digraphs rS " . 0x02b3')
  vim.cmd('execute "digraphs sS " . 0x02e2')
  vim.cmd('execute "digraphs tS " . 0x1d57')
  vim.cmd('execute "digraphs uS " . 0x1d58')
  vim.cmd('execute "digraphs vS " . 0x1d5b')
  vim.cmd('execute "digraphs wS " . 0x02b7')
  vim.cmd('execute "digraphs xS " . 0x02e3')
  vim.cmd('execute "digraphs yS " . 0x02b8')
  vim.cmd('execute "digraphs zS " . 0x1dbb')

  vim.cmd('execute "digraphs AS " . 0x1D2C')
  vim.cmd('execute "digraphs BS " . 0x1D2E')
  vim.cmd('execute "digraphs DS " . 0x1D30')
  vim.cmd('execute "digraphs ES " . 0x1D31')
  vim.cmd('execute "digraphs GS " . 0x1D33')
  vim.cmd('execute "digraphs HS " . 0x1D34')
  vim.cmd('execute "digraphs IS " . 0x1D35')
  vim.cmd('execute "digraphs JS " . 0x1D36')
  vim.cmd('execute "digraphs KS " . 0x1D37')
  vim.cmd('execute "digraphs LS " . 0x1D38')
  vim.cmd('execute "digraphs MS " . 0x1D39')
  vim.cmd('execute "digraphs NS " . 0x1D3A')
  vim.cmd('execute "digraphs OS " . 0x1D3C')
  vim.cmd('execute "digraphs PS " . 0x1D3E')
  vim.cmd('execute "digraphs RS " . 0x1D3F')
  vim.cmd('execute "digraphs TS " . 0x1D40')
  vim.cmd('execute "digraphs US " . 0x1D41')
  vim.cmd('execute "digraphs VS " . 0x2C7D')
  vim.cmd('execute "digraphs WS " . 0x1D42')
end

return M
