[wireless]
command=ip -br addr show wlp0s20f3 | awk '$2 == "UP" { cmd="iw dev wlp0s20f3 link"; while ((cmd | getline line) > 0) { if (line ~ /SSID/) ssid=$2; if (line ~ /tx bitrate/) bitrate=$3" "$4 } close(cmd); print "W: " ssid" "bitrate" "$3 }'
interval=5

[ethernet]
command=ip -br addr show enp0s31f6 | awk '$2 == "UP" {print "E: " $3}'
interval=5

[battery]
command=awk -F= '/^POWER_SUPPLY_STATUS=/ {s=$2} /^POWER_SUPPLY_CAPACITY=/ {p=$2} END {if (s == "Charging") print "⚡ CHR "p"%"; else if (s == "Discharging") print "🔋 BAT "p"%"; else if (s == "Full") print "FULL"; else print "? UNK"}' /sys/class/power_supply/BAT0/uevent
interval=5

[memory]
command=free -h | awk '/^Mem:/ {printf "M: %s/%s", $7, $2}'
interval=5

[cpu]
command=top -bn1 | awk '/Cpu\(s\)/ {printf "cpu: %d%%", $2+$4}'
interval=5

[volume-mic]
command=amixer -D default get Capture | awk -F'[][]' '/%/ {v=$2; s=$4} END {if (v != "") print "mic: "v}'
interval=5

[volume-master]
command=amixer -D default get Master | awk -F'[][]' '/%/ {v=$2; s=$4} END {if (s == "off") print "🕩 (mute)"; else print "🕪 ("v")"}'
interval=5

[disk-root]
command=df -h / | awk 'NR==2 {print "root: " $4 "/" $2}'
interval=5

[disk-data]
command=df -h /data | awk 'NR==2 {print "Data: " $4}'
interval=5

[eastern]
command=TZ=US/Eastern date '+ET:(%a) %H:%M'
interval=5

[local]
command=date '+%Y-%m-%d (%a) %H:%M:%S'
interval=1

[kanata-mode]
command=cat /home/ccw/.cache/kanata-mode
interval=1

